### ISSUE TITLE
Please make it so I can click on the title and it changes the language

### ISSUE THREAD

**Issue by evrhel** [yayabosh/one-hundred-percent#1]
It would be very cool

**Comment by yayabosh** [comment]
Hey Ethan, thanks for the issue! Do you want it to change language or do you want it to change the font like it does on page refresh right now? Changing language would be an entirely new feature, but could be really cool!

**Comment by evrhel** [comment]
Hi, I meant that the title would change automatically or by clicking on it so we don't have to refresh the page to change the font.

**Comment by yayabosh** [comment]
Hey Ethan, this issue has been resolved. You can see the updated feature on the website now!
